### ISSUE TITLE
Consider caching album artwork

### ISSUE THREAD

**Issue by LeviSnoot** [FNFestival/fnfestival.github.io#1]
Hi! This repo has been very helpful as inspiration for my own projects, so i wanted to contribute back by suggesting a potential issue with the way `fnfestival.co` currently serves album artwork from the game.

While working on my own projects I've been adamant in ensuring that it makes as few calls to Epic's servers as possible by caching the data elsewhere and having my project call that API instead (similarly to what this project does). Whilst testing the code I noticed early on that fetching the album art directly from Epic's servers can be an issue as they do seem to have rate limits imposed for unauthenticated clients at least (which you are when loading content from `cdn2.unrealengine.com` in a web browser). 

Since the website serves the album art directly from Epic's servers, this could actually lead to the user being rate limited and thus unable to play Fortnite Festival and/or other game modes for a time since the rate limit makes the user unable to fetch the data the game itself needs to be playable. I only hit that rate limit once and immediately made sure it wouldn't happen again, so I don't know specifically what the limit is, but I think it's sensible to cache the artwork anyways.

I'm happy to help set up a solution if that is of interest.

**Comment by FNFestival** [comment]
Hi, thanks for your suggestion! I couldn't find a rate limit yet though, and it wouldn't make sense if there was one, since a lot of Fortnite content loads from that URL itself.

Anyway, one problem if we hosted the covers ourselves would be if they were changed in the future. But as I said, even after reloading the page several times with cache disabled, I can't see any rate limits.
